FROM tensorflow/tensorflow:1.0.0
MAINTAINER Namju Kim buriburisuri@gmail.com

# requirements
RUN pip install --upgrade pip
RUN pip install sugartensor==0.0.2.5

# make example directory
RUN mkdir -p /root/sugartensor/example
ADD sugartensor/example/* /root/sugartensor/example/

# set default directory to sugar tensor's example directory
WORKDIR /root/sugartensor/example

# port export
EXPOSE 8888
